// examples/angular/src/app/components/visualizations/visualizations.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { RVConfiguration, RVReportTypes, RVOptions } from '@railzai/railz-visualizations';
import { cloneDeep } from 'lodash';

import { Filter } from '../../../types/form-submission';

@Component({
  selector: 'app-visualizations',
  templateUrl: './visualizations.component.html',
  styleUrls: ['./visualizations.component.css'],
})
export class VisualizationsComponent implements OnInit {
  @Input() configuration: RVConfiguration;
  @Input() filter: Filter;
  @Input() options: RVOptions;

  allReportTypes = Object.values(RVReportTypes);

  constructor() {}

  ngOnInit(): void {}

  getNewFilter = (filter: Filter, reportType: any): Filter => <Filter>{ ...filter, reportType };

  getNewOptions = (options: RVOptions, elementIndex: number): RVOptions => {
    const cloneOptions = cloneDeep(options);
    if (elementIndex !== 0) {
      delete cloneOptions?.content?.title;
    }
    return cloneOptions;
  };
}

<p *ngIf="!!configuration && !filter">No Filter, submit your filter details</p>
<p *ngIf="!configuration && !!filter">No Token, submit your authentication details</p>
<p *ngIf="!configuration && !filter">
  No Token and Filter, submit your authentication and filter information
</p>
<div *ngIf="!!configuration && !!filter">
  <div
    class="md:grid md:grid-cols-1 md:gap-1"
    *ngIf="filter?.reportType === 'all'; else statements"
  >
    <div
      class="col-span-1 mt-1"
      *ngFor="let reportType of allReportTypes; let elementIndex = index"
    >
      <railz-visualizations
        [configuration]="configuration"
        [filter]="getNewFilter(filter, reportType)"
        [options]="getNewOptions(options, elementIndex)"
      >
      </railz-visualizations>
    </div>
  </div>
</div>
<ng-template #statements>
  <div
    class="md:grid md:grid-cols-1 md:gap-1 text-left"
    *ngIf="filter?.reportType === 'balanceSheets'; else transactions"
  >
    <h4 class="text-xl font-bold text-gray-900">Using Railz Statements Chart Component</h4>
    <p>
      Railz Statements Chart Component only accepts <b>balanceSheets</b>,
      <b>cashflowStatements</b> and <b>incomeStatements</b>
    </p>
    <railz-statements-chart [configuration]="configuration" [filter]="filter" [options]="options">
    </railz-statements-chart>
  </div>
</ng-template>
<ng-template #transactions>
  <div
    class="md:grid md:grid-cols-1 md:gap-1 text-left"
    *ngIf="filter?.reportType === 'bills'; else financialRatios"
  >
    <h4 class="text-xl font-bold text-gray-900">Using Railz Transactions Control Component</h4>
    <p>
      Railz Transactions Control Component only accepts <b>bills</b> and
      <b>invoices</b>
    </p>
    <railz-transactions-control
      [configuration]="configuration"
      [filter]="filter"
      [options]="options"
    >
    </railz-transactions-control>
  </div>
</ng-template>
<ng-template #financialRatios>
  <div
    class="md:grid md:grid-cols-1 md:gap-1 text-left"
    *ngIf="filter?.reportType === 'financialRatios'; else incomeStatements"
  >
    <h4 class="text-xl font-bold text-gray-900">Using Railz Financial Ratios Component</h4>
    <p>Railz Financial Ratios Component only accepts <b>financialRatios</b></p>
    <railz-financial-ratios [configuration]="configuration" [filter]="filter" [options]="options">
    </railz-financial-ratios>
  </div>
</ng-template>
<ng-template #incomeStatements>
  <div
    class="md:grid md:grid-cols-1 md:gap-1 text-left"
    *ngIf="['expenses', 'revenue'].includes('' + filter?.reportType); else creditScore"
  >
    <h4 class="text-xl font-bold text-gray-900">Using Railz Pie Chart Component</h4>
    <p>Railz Income Statements Component only accepts <b>expenses</b> and <b>revenue</b></p>
    <railz-income-statements [configuration]="configuration" [filter]="filter" [options]="options">
    </railz-income-statements>
  </div>
</ng-template>
<ng-template #creditScore>
  <div
    class="md:grid md:grid-cols-1 md:gap-1 text-left"
    *ngIf="['creditScore'].includes('' + filter?.reportType); else bankAccounts"
  >
    <h4 class="text-xl font-bold text-gray-900">Using Railz Gauge Component</h4>
    <p>Railz Credit Score Component only accepts <b>creditScore</b></p>
    <railz-credit-score [configuration]="configuration" [filter]="filter" [options]="options">
    </railz-credit-score>
  </div>
</ng-template>
<ng-template #bankAccounts>
  <div
    class="md:grid md:grid-cols-1 md:gap-1 text-left"
    *ngIf="filter?.reportType === 'bankAccounts'; else bankReconciliation"
  >
    <h4 class="text-xl font-bold text-gray-900">Using Railz Bank Accounts Component</h4>
    <p>Railz Bank Accounts Component only accepts <b>bankAccounts</b></p>
    <railz-bank-accounts [configuration]="configuration" [filter]="filter" [options]="options">
    </railz-bank-accounts>
  </div>
</ng-template>
<ng-template #bankReconciliation>
  <div
    class="md:grid md:grid-cols-1 md:gap-1 text-left"
    *ngIf="filter?.reportType === 'bankReconciliation'; else businessValuations"
  >
    <h4 class="text-xl font-bold text-gray-900">Using Railz Bank Accounts Component</h4>
    <p>Railz Bank Accounts Component only accepts <b>bankReconciliation</b></p>
    <railz-bank-reconciliation
      [configuration]="configuration"
      [filter]="filter"
      [options]="options"
    >
    </railz-bank-reconciliation>
  </div>
</ng-template>
<ng-template #businessValuations>
  <div
    class="md:grid md:grid-cols-1 md:gap-1 text-left"
    *ngIf="filter?.reportType === 'businessValuations'; else visualizations"
  >
    <h4 class="text-xl font-bold text-gray-900">Using Railz Business Valuations Component</h4>
    <p>Railz Bank Accounts Component only accepts <b>businessValuations</b></p>
    <railz-business-valuations
      [configuration]="configuration"
      [filter]="filter"
      [options]="options"
    >
    </railz-business-valuations>
  </div>
</ng-template>
<ng-template #visualizations>
  <div class="md:grid md:grid-cols-1 md:gap-1 text-left">
    <h4 class="text-xl font-bold text-gray-900">Using Railz Visualizations Component</h4>
    <railz-visualizations [configuration]="configuration" [filter]="filter" [options]="options">
    </railz-visualizations>
  </div>
</ng-template>

// examples/react-example/src/components/visualizations.tsx
import React, { useState } from 'react';
import {
  RVConfiguration,
  RVOptions,
  RVReportFrequency,
  RVReportTypes,
  RVServiceProviders,
  RVFilterFinancialRatio,
  RVFilterIncomeStatementsType,
  RVFilterStatements,
  RVFilterTransactions,
  RVFilterAll,
  RVFilterBankAccount,
  RVFilterCreditScore,
  RVFilterBankReconciliation,
} from '@railzai/railz-visualizations';
import {
  RailzBankAccounts,
  RailzFinancialRatios,
  RailzCreditScore,
  RailzIncomeStatements,
  RailzStatementsChart,
  RailzTransactionsControl,
  RailzVisualizations,
} from '@railzai/railz-visualizations-react';
import { cloneDeep, isEmpty, pick } from 'lodash';
import { RailzBankReconciliation } from '@railzai/railz-visualizations-react';

type AllTypes = 'all' & RVReportTypes;

interface Filter {
  businessName?: string;
  serviceName?: RVServiceProviders;
  connectionId?: string;
  startDate: string;
  endDate: string;
  reportFrequency: RVReportFrequency;
  reportType: AllTypes;
}

interface ChartProps {
  configuration: RVConfiguration;
  filter: Filter;
  options?: RVOptions;
  showCode?: boolean;
  displayValue?: string;
}
const formatCodeFilter = (filter: Filter) => {
  let allParameters;
  if ([RVReportTypes.BILLS, RVReportTypes.INVOICES].includes(filter.reportType)) {
    if (!isEmpty(filter?.connectionId)) {
      allParameters = pick(filter, ['startDate', 'endDate', 'reportType', 'connectionId']);
    } else {
      allParameters = pick(filter, [
        'startDate',
        'endDate',
        'businessName',
        'reportType',
        'serviceName',
      ]);
    }
  } else {
    if (!isEmpty(filter?.connectionId)) {
      allParameters = pick(filter, [
        'startDate',
        'endDate',
        'reportFrequency',
        'reportType',
        'connectionId',
      ]);
    } else {
      allParameters = pick(filter, [
        'startDate',
        'endDate',
        'reportFrequency',
        'reportType',
        'businessName',
        'serviceName',
      ]);
    }
  }
  return allParameters;
};

const Code = ({ configuration, filter, options, showCode, displayValue }: ChartProps) => {
  return (
    <>
      {showCode && (
        <pre className="language-html bg-black text-white mt-4 p-4 rounded-xl overflow-hidden">
          <code className="language-html">
            {'<' +
              displayValue +
              ' configuration={' +
              JSON.stringify({ token: configuration.token.slice(0, 20) + '...' }, null, '\t') +
              '} filter={' +
              JSON.stringify(formatCodeFilter(filter) as any, null, '\t') +
              `${options ? '} options={' + JSON.stringify(options, null, '\t') : ''}} />`}
          </code>
        </pre>
      )}
    </>
  );
};

const DefaultComponent = ({ configuration, filter, options, showCode }: ChartProps) => {
  return (
    <div>
      <RailzVisualizations
        configuration={configuration}
        filter={filter as unknown as RVFilterAll}
        options={options}
      />
      <Code
        configuration={configuration}
        filter={filter}
        options={options}
        showCode={showCode}
        displayValue="RailzVisualizations"
      />
    </div>
  );
};

const Components = ({ configuration, filter, options, showCode }: ChartProps) => {
  return (
    <div className="mt-5 md:grid md:grid-cols-1 md:gap-1">
      {/*Switch to Object.values(RVReportTypes) when all is implemented*/}
      {filter.reportType === 'all' &&
        [
          RVReportTypes.BILLS,
          RVReportTypes.INVOICES,
          RVReportTypes.BALANCE_SHEET,
          RVReportTypes.INCOME_STATEMENTS,
          RVReportTypes.CASHFLOW_STATEMENTS,
          RVReportTypes.EXPENSES,
          RVReportTypes.REVENUE,
          RVReportTypes.CREDIT_SCORE,
          RVReportTypes.FINANCIAL_RATIO,
          RVReportTypes.BANK_ACCOUNT,
          RVReportTypes.BANK_RECONCILIATION,
        ].map((reportType, index) => {
          const cloneOptions = cloneDeep(options);
          if (index !== 0) {
            delete cloneOptions?.content?.title;
          }
          return (
            <div className="col-span-1 mt-1" key={reportType}>
              <DefaultComponent
                configuration={configuration}
                filter={cloneDeep({ ...filter, reportType }) as Filter}
                options={cloneOptions}
                showCode={showCode}
              />
            </div>
          );
        })}
      {[RVReportTypes.CREDIT_SCORE].includes(filter.reportType) && (
        <div>
          <h4 className="text-xl font-bold text-gray-900">Using Railz Credit Score Component</h4>
          <p>
            Railz Credit Score Component only accepts <b>creditScore</b>
          </p>
          <RailzCreditScore
            configuration={configuration}
            filter={filter as RVFilterCreditScore}
            options={options}
          />
          <Code
            configuration={configuration}
            filter={filter}
            options={options}
            showCode={showCode}
            displayValue="RailzCreditScore"
          />
        </div>
      )}
      {filter.reportType === RVReportTypes.EXPENSES && (
        <div>
          <h4 className="text-xl font-bold text-gray-900">Using Railz Pie Chart Component</h4>
          <p>
            Railz Pie Chart Component only accepts <b>expenses</b> and <b>revenues</b>
          </p>
          <RailzIncomeStatements
            configuration={configuration}
            filter={filter as RVFilterIncomeStatementsType}
            options={options}
          />
          <Code
            configuration={configuration}
            filter={filter}
            options={options}
            showCode={showCode}
            displayValue="RailzIncomeStatements"
          />
        </div>
      )}
      {filter.reportType === RVReportTypes.BALANCE_SHEET && (
        <div>
          <h4 className="text-xl font-bold text-gray-900">
            Using Railz Statements Chart Component
          </h4>
          <p>
            Railz Statements Chart Component only accepts <b>balanceSheets</b>,{' '}
            <b>cashflowStatements</b> and <b>incomeStatements</b>
          </p>
          <RailzStatementsChart
            configuration={configuration}
            filter={filter as RVFilterStatements}
            options={options}
          />
          <Code
            configuration={configuration}
            filter={filter}
            options={options}
            showCode={showCode}
            displayValue="RailzStatementsChart"
          />
        </div>
      )}
      {filter.reportType === RVReportTypes.BILLS && (
        <div>
          <h4 className="text-xl font-bold text-gray-900">
            Using Railz Transactions Control Component
          </h4>
          <p>
            Railz Transactions Control Component only accepts <b>bills</b> and <b>invoices</b>
          </p>
          <RailzTransactionsControl
            configuration={configuration}
            filter={filter as RVFilterTransactions}
            options={options}
          />
          <Code
            configuration={configuration}
            filter={filter}
            options={options}
            showCode={showCode}
            displayValue="RailzTransactionsControl"
          />
        </div>
      )}
      {[RVReportTypes.FINANCIAL_RATIO].includes(filter.reportType) && (
        <div>
          <h4 className="text-xl font-bold text-gray-900">Using Railz FinancialRatios Component</h4>
          <p>
            Railz Financial Ratios Component only accepts <b>financialRatios</b>
          </p>
          <RailzFinancialRatios
            configuration={configuration}
            filter={filter as RVFilterFinancialRatio}
            options={options}
          />
          <Code
            configuration={configuration}
            filter={filter}
            options={options}
            showCode={showCode}
            displayValue="RailzFinancialRatios"
          />
        </div>
      )}
      {filter.reportType === RVReportTypes.BANK_ACCOUNT && (
        <div>
          <h4 className="text-xl font-bold text-gray-900">Using Railz Bank Accounts Component</h4>
          <p>
            Railz Bank Accounts Component only accepts <b>bankAccounts</b>
          </p>
          <RailzBankAccounts
            configuration={configuration}
            filter={filter as RVFilterBankAccount}
            options={options}
          />
          <Code
            configuration={configuration}
            filter={filter}
            options={options}
            showCode={showCode}
            displayValue="RailzBankAccounts"
          />
        </div>
      )}
      {filter.reportType === RVReportTypes.BANK_RECONCILIATION && (
        <div>
          <h4 className="text-xl font-bold text-gray-900">
            Using Railz Bank Reconciliation Component
          </h4>
          <p>
            Railz Bank Reconciliation Component only accepts <b>bankReconciliation</b>
          </p>
          <RailzBankReconciliation
            configuration={configuration}
            filter={filter as RVFilterBankReconciliation}
            options={options}
          />
          <Code
            configuration={configuration}
            filter={filter}
            options={options}
            showCode={showCode}
            displayValue="RailzReconciliation"
          />
        </div>
      )}
      {![
        RVReportTypes.CREDIT_SCORE,
        RVReportTypes.EXPENSES,
        RVReportTypes.BALANCE_SHEET,
        RVReportTypes.BILLS,
        RVReportTypes.FINANCIAL_RATIO,
        RVReportTypes.BANK_ACCOUNT,
        RVReportTypes.BANK_RECONCILIATION,
        'all',
      ].includes(filter.reportType) && (
        <DefaultComponent
          configuration={configuration}
          filter={filter}
          options={options}
          showCode={showCode}
        />
      )}
    </div>
  );
};
export default function Visualizations({ configuration, filter, options }: ChartProps) {
  const [code, setCode] = useState(false);
  return (
    <div className="md:grid md:grid-cols-1 md:gap-1 text-left">
      <div className="col-span-1 flex justify-end">
        <label htmlFor="switch-code">
          <input
            checked={code}
            onChange={() => setCode(!code)}
            className=" w-9 -ml-10 rounded-full h-5 align-top bg-white bg-no-repeat bg-contain bg-gray-500 focus:outline-none cursor-pointer shadow-sm"
            type="checkbox"
            role="switch"
            id="switch-code"
          />
          <span className="text-gray-800 ml-2"> Show Code Example</span>
        </label>
      </div>
      <Components configuration={configuration} filter={filter} options={options} showCode={code} />
    </div>
  );
}
