// examples/react/src/components/form/elements/auth-form.tsx
import React, { useState } from 'react';
import { AuthenticationParameters } from '../../../types/authentication';
import { FormProps } from '../../../types/form';

export default function AuthForm({ setAuthentication, setError }: FormProps) {
  const [formAuth, setFormAuth] = useState<AuthenticationParameters>({
    authUrl: '',
  });

  const submitAuth = async (event: any) => {
    event.preventDefault();
    if (formAuth.authUrl) {
      await setAuthentication(formAuth);
    } else {
      setError('Authentication details are required to get access configuration.');
    }
  };

  const handleAuthChange = (event: any) => {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    setFormAuth({ ...formAuth, [name]: value });
  };

  return (
    <div className="flex flex-col">
      <div className="text-left">
        <h2 className="text-lg font-medium leading-6 text-gray-900">Authentication</h2>
        <p className="mt-1 text-sm text-gray-600">
          Include your Authentication server URL here, see our quickstart example{' '}
          <a
            href="https://github.com/railz-ai/railz-visualizations/tree/master/examples/nodejs"
            target="_blank"
            className="underline"
            rel="noopener noreferrer"
          >
            here
          </a>
          .
        </p>
        <p className="mt-1 text-sm text-gray-600 font-bold">This is not implemented by the SDK.</p>
      </div>
      <div className="mt-4 md:mt-2 text-left items-end">
        <form onSubmit={submitAuth} method="POST">
          <div className="overflow-hidden sm:rounded-md bg-white">
            <div className="grid grid-cols-6 gap-6 items-end">
              <div className="col-span-6 lg:col-span-6">
                <label htmlFor="api-url" className="block text-sm font-medium text-gray-700">
                  Auth Url
                </label>
                <input
                  type="text"
                  name="authUrl"
                  id="api-url"
                  required
                  placeholder="http://localhost:4000/authenticate"
                  onChange={handleAuthChange}
                  value={formAuth.authUrl}
                  className="mt-1 focus:ring-green-500 focus:border-green-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                />
              </div>

              <div className="col-span-6 lg:col-span-6 items-end">
                <button
                  type="submit"
                  className="inline-flex justify-center w-full place-items-end py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-700 hover:bg-green-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-800"
                >
                  Authenticate
                </button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}

// examples/angular/src/app/components/form/elements/auth-form/auth-form.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {FormGroup} from "@angular/forms";

@Component({
  selector: 'app-auth-form',
  templateUrl: './auth-form.component.html'
})
export class AuthFormComponent implements OnInit {
  @Input() authForm: FormGroup = new FormGroup({});
  @Output() authEvent = new EventEmitter<void>();

  constructor() { }

  ngOnInit(): void {
  }

  onSubmit() {
    if (this.authForm && this.authForm.valid) {
      this.authEvent.emit();
    }
  }
}

<div class="flex flex-col">

  <div class="text-left">
    <h2 class="text-lg font-medium leading-6 text-gray-900">Authentication</h2>
    <p class="mt-1 text-sm text-gray-600">Include your Authentication server URL here, see our quickstart example <a
      href="https://github.com/railz-ai/railz-visualizations/tree/master/examples/nodejs" target="_blank"
      class="underline" rel="noopener noreferrer">here</a>.</p>
    <p class="mt-1 text-sm text-gray-600 font-bold">This is not implemented by the SDK.</p>
  </div>
  <div class="mt-4 md:mt-3 text-left items-end">
    <form [formGroup]="authForm" (ngSubmit)="onSubmit()">
      <div class="overflow-hidden sm:rounded-md">
        <div class="grid grid-cols-6 gap-6 items-end">
          <div class="col-span-6 sm:col-span-6">
            <label for="auth-url" class="block text-sm font-medium text-gray-700">Auth Url</label>
            <input formControlName="authUrl" type="text" name="auth-url" id="auth-url"
                   class="mt-1 focus:ring-green-500 focus:border-green-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                   placeholder="http://localhost:4000/authenticate">
          </div>
          <div class="col-span-6 lg:col-span-6 items-end">
            <button type="submit"
                    class="w-full inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">
              Authenticate
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
